# Generated by Django 4.1.1 on 2022-10-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteonv3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_users',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
