# Generated by Django 4.1.1 on 2022-10-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteonv3', '0003_tb_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_notas',
            name='cor',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
